import pg from "pg";
import { DataTypes, Sequelize } from "sequelize";

import { config } from "../config.ts";
import { logger } from "../logger.ts";

export const sequelize = new Sequelize({
  host: config.db.host,
  dialect: "postgres",
  dialectModule: pg,
  logging: false,
  username: config.db.user,
  password: config.db.password as string,
  database: config.db.name,
  pool: {
    max: 15,
    min: 0,
    acquire: 30000,
    idle: 10000,
  },
});

export const VideoMetadata = sequelize.define("video_metadata", {
  videoUrl: {
    type: DataTypes.STRING,
    allowNull: false,
    primaryKey: true,
  },
  videoId: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "YouTube/platform-specific video identifier",
  },
  title: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  approximateSize: {
    type: DataTypes.BIGINT,
    allowNull: false,
    comment: "Estimated file size in bytes",
  },
  downloadStatus: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
    comment: "Whether video has been downloaded",
  },
  isAvailable: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: true,
    comment: "Whether video is still available on platform",
  },
  fileName: {
    type: DataTypes.STRING,
    allowNull: true,
    comment:
      "Name of the file on disk, should have the extension. null if not downloaded.",
  },
  thumbNailFile: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: "Thumbnail generated by yt-dlp",
  },
  onlineThumbnail: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment:
      "Online thumbnail URL scraped from yt-dlp, used as fallback when thumbNailFile is not available. TEXT type because some CDN URLs exceed 255 chars.",
  },
  subTitleFile: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: "Subtitle generated by yt-dlp",
  },
  commentsFile: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: "Comments file generated by yt-dlp",
  },
  descriptionFile: {
    type: DataTypes.STRING,
    allowNull: true,
    comment:
      "Description retrieved by yt-dlp, not sure yet if I will save the path or read the data and save it here.",
  },
  isMetaDataSynced: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
    comment:
      "This will serve as a marker for other processes to know if they need to sync metadata from downloaded files",
  },
  saveDirectory: {
    type: DataTypes.STRING,
    allowNull: true,
    defaultValue: null,
    comment:
      "Directory relative to saveLocation where files are stored. null if not downloaded, empty string for root.",
  },
  raw_metadata: {
    type: DataTypes.JSONB,
    allowNull: true,
    comment:
      "Full pruned yt-dlp JSON output for future use (tags, age rating, etc). Bulky arrays like formats/thumbnails/subtitles are removed before storage.",
  },
  createdAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
}, {
  defaultScope: {
    attributes: { exclude: ["raw_metadata"] },
  },
});

export const PlaylistMetadata = sequelize.define("playlist_metadata", {
  playlistUrl: {
    type: DataTypes.STRING,
    allowNull: false,
    primaryKey: true,
  },
  title: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  sortOrder: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0,
    comment: "Order in which playlists are displayed",
  },
  monitoringType: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "Type of monitoring applied to playlist",
  },
  saveDirectory: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "Directory path for downloaded videos",
  },
  createdAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  lastUpdatedByScheduler: {
    type: DataTypes.DATE,
    allowNull: false,
    comment:
      "Timestamp of the last update made by the scheduler, default value is createdAt",
  },
});

export const PlaylistVideoMapping = sequelize.define("playlist_video_mapping", {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
    allowNull: false,
  },
  videoUrl: {
    type: DataTypes.STRING,
    allowNull: false,
    references: {
      model: VideoMetadata,
      key: "videoUrl",
    },
    onUpdate: "CASCADE",
    onDelete: "CASCADE",
    comment: "Foreign key linking to VideoMetadata",
  },
  playlistUrl: {
    type: DataTypes.STRING,
    allowNull: false,
    references: {
      model: PlaylistMetadata,
      key: "playlistUrl",
    },
    onUpdate: "CASCADE",
    onDelete: "CASCADE",
    comment: "Foreign key linking to PlaylistMetadata",
  },
  positionInPlaylist: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0,
    comment: "Order of video within playlist",
  },
}, {
  indexes: [
    {
      fields: ["playlistUrl", "positionInPlaylist"],
    },
  ],
});

export const UserAccount = sequelize.define("user_account", {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
    allowNull: false,
  },
  username: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: true,
  },
  passwordHash: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "Hashed password using bcrypt",
  },
  passwordSalt: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "Salt used in password hashing",
  },
});

PlaylistVideoMapping.belongsTo(VideoMetadata, {
  foreignKey: "videoUrl",
});

PlaylistVideoMapping.belongsTo(PlaylistMetadata, {
  foreignKey: "playlistUrl",
});

VideoMetadata.hasMany(PlaylistVideoMapping, {
  foreignKey: "videoUrl",
});

PlaylistMetadata.hasMany(PlaylistVideoMapping, {
  foreignKey: "playlistUrl",
});

export async function initializeDatabase() {
  try {
    await sequelize.authenticate();
    logger.info("Connection to database has been established successfully", {
      host: config.db.host,
      database: config.db.name,
    });
  } catch (error) {
    logger.error("Unable to connect to the database", {
      host: config.db.host,
      database: config.db.name,
      error: (error as Error).message,
    });
    throw error;
  }

  try {
    await sequelize.sync({ alter: true });

    logger.info("tables exist or are created successfully", {
      host: config.db.host,
      database: config.db.name,
      tables: JSON.stringify([
        (VideoMetadata as unknown as { name: string }).name,
        (PlaylistMetadata as unknown as { name: string }).name,
        (PlaylistVideoMapping as unknown as { name: string }).name,
      ]),
    });

    try {
      await sequelize.query("CREATE EXTENSION IF NOT EXISTS pg_trgm;");
      await sequelize.query(
        "CREATE INDEX IF NOT EXISTS idx_video_metadata_title_trgm ON video_metadata USING gin (title gin_trgm_ops);",
      );
      await sequelize.query(
        "CREATE INDEX IF NOT EXISTS idx_playlist_metadata_title_trgm ON playlist_metadata USING gin (title gin_trgm_ops);",
      );
      logger.info("Trigram indexes checked/created successfully");
    } catch (err) {
      logger.error("Failed to create Trigram indexes", {
        error: (err as Error).message,
      });
    }

    const [unlistedPlaylist, created] = await PlaylistMetadata.findOrCreate({
      where: { playlistUrl: "None" },
      defaults: {
        title: "None",
        monitoringType: "N/A",
        saveDirectory: "",
        lastUpdatedByScheduler: new Date(0),
        sortOrder: -1,
      },
    });

    if (created) {
      logger.info("Unlisted playlist created successfully", {
        host: config.db.host,
        database: config.db.name,
        tables: JSON.stringify([
          (unlistedPlaylist as unknown as { name: string }).name,
        ]),
      });
    }

    const defaultUserCheck = await UserAccount.count();
    if (defaultUserCheck === 0) {
      logger.warn(
        "No users exist in the database. Please create a user account.",
        { setup_required: true },
      );
    } else {
      logger.info("Users exist in database", {
        user_count: defaultUserCheck,
      });
    }
  } catch (error) {
    logger.error("Unable to create table", { error: error as Error });
  }
}
