import pg from "pg";
import { DataTypes, Model, Sequelize } from "sequelize";
import type {
  CreationOptional,
  InferAttributes,
  InferCreationAttributes,
} from "sequelize";

import { config } from "../config.ts";
import { logger } from "../logger.ts";

export const sequelize = new Sequelize({
  host: config.db.host,
  dialect: "postgres",
  dialectModule: pg,
  logging: false,
  username: config.db.user,
  password: config.db.password as string,
  database: config.db.name,
  pool: {
    max: 15,
    min: 0,
    acquire: 30000,
    idle: 10000,
  },
});

export class VideoMetadata extends Model<
  InferAttributes<VideoMetadata>,
  InferCreationAttributes<VideoMetadata>
> {
  declare videoUrl: string;
  declare videoId: string;
  declare title: string;
  declare approximateSize: number | string;
  declare downloadStatus: CreationOptional<boolean>;
  declare isAvailable: CreationOptional<boolean>;
  declare fileName: CreationOptional<string | null>;
  declare thumbNailFile: CreationOptional<string | null>;
  declare onlineThumbnail: CreationOptional<string | null>;
  declare subTitleFile: CreationOptional<string | null>;
  declare commentsFile: CreationOptional<string | null>;
  declare descriptionFile: CreationOptional<string | null>;
  declare isMetaDataSynced: CreationOptional<boolean>;
  declare saveDirectory: CreationOptional<string | null>;
  declare raw_metadata: CreationOptional<unknown>;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;
}

VideoMetadata.init({
  videoUrl: {
    type: DataTypes.STRING,
    allowNull: false,
    primaryKey: true,
  },
  videoId: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "YouTube/platform-specific video identifier",
  },
  title: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  approximateSize: {
    type: DataTypes.BIGINT,
    allowNull: false,
    comment: "Estimated file size in bytes",
  },
  downloadStatus: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
    comment: "Whether video has been downloaded",
  },
  isAvailable: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: true,
    comment: "Whether video is still available on platform",
  },
  fileName: {
    type: DataTypes.STRING,
    allowNull: true,
    comment:
      "Name of the file on disk, should have the extension. null if not downloaded.",
  },
  thumbNailFile: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: "Thumbnail generated by yt-dlp",
  },
  onlineThumbnail: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment:
      "Online thumbnail URL scraped from yt-dlp, used as fallback when thumbNailFile is not available. TEXT type because some CDN URLs exceed 255 chars.",
  },
  subTitleFile: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: "Subtitle generated by yt-dlp",
  },
  commentsFile: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: "Comments file generated by yt-dlp",
  },
  descriptionFile: {
    type: DataTypes.STRING,
    allowNull: true,
    comment:
      "Description retrieved by yt-dlp, not sure yet if I will save the path or read the data and save it here.",
  },
  isMetaDataSynced: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
    comment:
      "This will serve as a marker for other processes to know if they need to sync metadata from downloaded files",
  },
  saveDirectory: {
    type: DataTypes.STRING,
    allowNull: true,
    defaultValue: null,
    comment:
      "Directory relative to saveLocation where files are stored. null if not downloaded, empty string for root.",
  },
  raw_metadata: {
    type: DataTypes.JSONB,
    allowNull: true,
    comment:
      "Full pruned yt-dlp JSON output for future use (tags, age rating, etc). Bulky arrays like formats/thumbnails/subtitles are removed before storage.",
  },
  createdAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
}, {
  sequelize,
  modelName: "video_metadata",
  defaultScope: {
    attributes: { exclude: ["raw_metadata"] },
  },
  indexes: [
    {
      fields: ["videoId"],
      unique: false,
      name: "idx_video_metadata_video_id",
    },
  ],
});

export class PlaylistMetadata extends Model<
  InferAttributes<PlaylistMetadata>,
  InferCreationAttributes<PlaylistMetadata>
> {
  declare playlistUrl: string;
  declare title: string;
  declare sortOrder: CreationOptional<number>;
  declare monitoringType: string;
  declare saveDirectory: string;
  declare lastUpdatedByScheduler: Date;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;
}

PlaylistMetadata.init({
  playlistUrl: {
    type: DataTypes.STRING,
    allowNull: false,
    primaryKey: true,
  },
  title: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  sortOrder: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0,
    comment: "Order in which playlists are displayed",
  },
  monitoringType: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "Type of monitoring applied to playlist",
  },
  saveDirectory: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "Directory path for downloaded videos",
  },
  createdAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  lastUpdatedByScheduler: {
    type: DataTypes.DATE,
    allowNull: false,
    comment:
      "Timestamp of the last update made by the scheduler, default value is createdAt",
  },
}, {
  sequelize,
  modelName: "playlist_metadata",
});

export class PlaylistVideoMapping extends Model<
  InferAttributes<PlaylistVideoMapping>,
  InferCreationAttributes<PlaylistVideoMapping>
> {
  declare id: CreationOptional<string>;
  declare videoUrl: string;
  declare playlistUrl: string;
  declare positionInPlaylist: CreationOptional<number>;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  declare video_metadatum?: VideoMetadata;
}

PlaylistVideoMapping.init({
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
    allowNull: false,
  },
  videoUrl: {
    type: DataTypes.STRING,
    allowNull: false,
    references: {
      model: VideoMetadata,
      key: "videoUrl",
    },
    onUpdate: "CASCADE",
    onDelete: "CASCADE",
    comment: "Foreign key linking to VideoMetadata",
  },
  playlistUrl: {
    type: DataTypes.STRING,
    allowNull: false,
    references: {
      model: PlaylistMetadata,
      key: "playlistUrl",
    },
    onUpdate: "CASCADE",
    onDelete: "CASCADE",
    comment: "Foreign key linking to PlaylistMetadata",
  },
  positionInPlaylist: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0,
    comment: "Order of video within playlist",
  },
  createdAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
}, {
  sequelize,
  modelName: "playlist_video_mapping",
  indexes: [
    {
      fields: ["playlistUrl", "positionInPlaylist"],
    },
  ],
});

export class UserAccount extends Model<
  InferAttributes<UserAccount>,
  InferCreationAttributes<UserAccount>
> {
  declare id: CreationOptional<string>;
  declare username: string;
  declare passwordHash: string;
  declare passwordSalt: string;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;
}

UserAccount.init({
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
    allowNull: false,
  },
  username: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: true,
  },
  passwordHash: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "Hashed password using bcrypt",
  },
  passwordSalt: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "Salt used in password hashing",
  },
  createdAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
}, {
  sequelize,
  modelName: "user_account",
});

/**
 * One chat-bot request, from the message that arrived to the file that was
 * delivered.
 *
 * Kept deliberately separate from VideoMetadata so that submission history
 * survives a video being deleted from the web UI, and so the retention reaper
 * can tell — in SQL rather than by convention — which files the bot actually
 * fetched versus which already existed when it was asked.
 */
export class BotSubmission extends Model<
  InferAttributes<BotSubmission>,
  InferCreationAttributes<BotSubmission>
> {
  declare id: CreationOptional<string>;
  declare platform: string;
  declare chatId: string;
  declare messageId: CreationOptional<string | null>;
  declare requestedUrl: string;
  declare canonicalUrl: CreationOptional<string | null>;
  declare kind: string;
  declare playlistUrl: CreationOptional<string | null>;
  declare status: CreationOptional<string>;
  declare deliveryMode: CreationOptional<string | null>;
  declare retention: CreationOptional<string>;
  declare downloadedByBot: CreationOptional<boolean>;
  declare expiresAt: CreationOptional<Date | null>;
  declare errorMessage: CreationOptional<string | null>;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;
}

BotSubmission.init({
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
    allowNull: false,
  },
  platform: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: 'Originating chat platform: "telegram" or "discord"',
  },
  chatId: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "Platform chat/channel the request came from",
  },
  messageId: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: "Acknowledgement message edited in place as the request advances",
  },
  requestedUrl: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: "URL exactly as the user typed it",
  },
  canonicalUrl: {
    type: DataTypes.STRING,
    allowNull: true,
    references: {
      model: VideoMetadata,
      key: "videoUrl",
    },
    onUpdate: "CASCADE",
    // SET NULL, not CASCADE: deleting a video from the web UI must not erase
    // the record that the bot was once asked for it.
    onDelete: "SET NULL",
    comment: "Result of normalizeUrl(); foreign key linking to VideoMetadata",
  },
  kind: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: 'Whether the request was for a "video" or a "playlist"',
  },
  playlistUrl: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: "Playlist this submission belongs to, when applicable",
  },
  status: {
    type: DataTypes.STRING,
    allowNull: false,
    defaultValue: "pending",
    comment: "pending | indexing | downloading | delivered | failed | reaped",
  },
  deliveryMode: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: 'How the file reached the user: "upload" or "signed_url"',
  },
  retention: {
    type: DataTypes.STRING,
    allowNull: false,
    defaultValue: "ephemeral",
    comment: '"ephemeral" (reaped after expiry) or "persistent"',
  },
  downloadedByBot: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
    comment:
      "False when the file already existed; the reaper never deletes those",
  },
  expiresAt: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: "Null when persistent or when downloadedByBot is false",
  },
  errorMessage: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: "Reason recorded alongside status='failed'",
  },
  createdAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: DataTypes.DATE,
    allowNull: false,
  },
}, {
  sequelize,
  modelName: "bot_submission",
  indexes: [
    {
      // Drives the retention reaper's selection.
      fields: ["status", "expiresAt"],
    },
    {
      // Drives the submit-path dedupe lookup.
      fields: ["canonicalUrl"],
    },
  ],
});

PlaylistVideoMapping.belongsTo(VideoMetadata, {
  foreignKey: "videoUrl",
});

PlaylistVideoMapping.belongsTo(PlaylistMetadata, {
  foreignKey: "playlistUrl",
});

VideoMetadata.hasMany(PlaylistVideoMapping, {
  foreignKey: "videoUrl",
});

PlaylistMetadata.hasMany(PlaylistVideoMapping, {
  foreignKey: "playlistUrl",
});

export async function initializeDatabase() {
  try {
    await sequelize.authenticate();
    logger.info("Connection to database has been established successfully", {
      host: config.db.host,
      database: config.db.name,
    });
  } catch (error) {
    logger.error("Unable to connect to the database", {
      host: config.db.host,
      database: config.db.name,
      error: (error as Error).message,
    });
    throw error;
  }

  try {
    await sequelize.sync({ alter: true });

    logger.info("tables exist or are created successfully", {
      host: config.db.host,
      database: config.db.name,
      tables: JSON.stringify([
        VideoMetadata.name,
        PlaylistMetadata.name,
        PlaylistVideoMapping.name,
        BotSubmission.name,
      ]),
    });

    try {
      await sequelize.query("CREATE EXTENSION IF NOT EXISTS pg_trgm;");
      await sequelize.query(
        "CREATE INDEX IF NOT EXISTS idx_video_metadata_title_trgm ON video_metadata USING gin (title gin_trgm_ops);",
      );
      await sequelize.query(
        "CREATE INDEX IF NOT EXISTS idx_playlist_metadata_title_trgm ON playlist_metadata USING gin (title gin_trgm_ops);",
      );
      await sequelize.query(
        'CREATE INDEX IF NOT EXISTS idx_video_metadata_video_id ON video_metadata ("videoId");',
      );
      logger.info(
        "Trigram indexes and videoId index checked/created successfully",
      );
    } catch (err) {
      logger.error("Failed to create indexes", {
        error: (err as Error).message,
      });
    }

    const [_unlistedPlaylist, created] = await PlaylistMetadata.findOrCreate({
      where: { playlistUrl: "None" },
      defaults: {
        playlistUrl: "None",
        title: "None",
        monitoringType: "N/A",
        saveDirectory: "",
        lastUpdatedByScheduler: new Date(0),
        sortOrder: -1,
      },
    });

    if (created) {
      logger.info("Unlisted playlist created successfully", {
        host: config.db.host,
        database: config.db.name,
        tables: JSON.stringify([
          PlaylistMetadata.name,
        ]),
      });
    }

    const defaultUserCheck = await UserAccount.count();
    if (defaultUserCheck === 0) {
      logger.warn(
        "No users exist in the database. Please create a user account.",
        { setup_required: true },
      );
    } else {
      logger.info("Users exist in database", {
        user_count: defaultUserCheck,
      });
    }
  } catch (error) {
    logger.error("Unable to create table", { error: error as Error });
  }
}
